version: "3"

services:
  postgres:
    image: postgres
    build:
      dockerfile: ./postgresql/Dockerfile
    container_name: 'postgres'
    ports:
      - "5432:5432"
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: postgre
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

  python3:
    image: python3
    build:
      dockerfile: ./python/Dockerfile
    container_name: 'python3'
    tty: true
    environment:
        TZ: "Asia/Tokyo"
    volumes: 
      - ./python/data:/var/lib/python3/data
